### ISSUE TITLE
Empty NPM package

### ISSUE THREAD

**Issue by Makvagabo** [GevatterGaul/epubts#1]
Hey man! I really glad to see that someone made ts version of epubjs. I was looking for somethings like this. But there is a problem I guess. I know that is Github not npm. So anyway. It seems that something went wrong during publishing last version of your library.
I run command 
`yarn add epubts`
and see folder without the dist folder.
It is 0.1.4 version.

![image](https://github.com/user-attachments/assets/12608f87-beaf-4523-aa26-eb2b4dec5402)

**Comment by GevatterGaul** [comment]
Thx for raising this issue, I'm investigating where I lost the dist folder

**Comment by GevatterGaul** [comment]
Just uploaded version 0.1.5: https://www.npmjs.com/package/epubts/v/0.1.5 Can you check wether your problem is fixed?

**Comment by GevatterGaul** [comment]
I also merged your PR adding the events library. We should get rid of the node dependendy at some point though.
